# Generated by Django 4.2.9 on 2025-04-11 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=35)),
                ('region', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('address_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=60)),
                ('user_age', models.PositiveIntegerField(default=0)),
                ('gender', models.PositiveIntegerField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_avg_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activation_code', models.CharField(blank=True, max_length=8)),
                ('user_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.useraddress')),
                ('user_documents', models.ManyToManyField(to='account.document')),
                ('user_workplace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
