# Generated by Django 4.2.9 on 2025-04-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraddress_address_alter_useraddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='inn',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.useraddress'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_workplace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.workplace'),
        ),
    ]
